name: github actions

on:
  push:
    branches:
      - main

job:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.REMOTE_USER }}
          server-ip: ${{ secrets.SERVER_IP }}
          remote-path: ${{ secrets.REMOTE_PATH }}
          local-path: ./dist